export const RESET_STATE = 'RESET_STATE';
export const RESET_STORE = 'RESET_STORE';

export const METRICS_ONE_LIST_REQUEST = 'METRICS_ONE_LIST_REQUEST';
export const METRICS_ONE_LIST_FILTER_REQUEST = 'METRICS_ONE_LIST_FILTER_REQUEST';
export const METRICS_ONE_LIST_CHARGING = 'METRICS_ONE_LIST_CHARGING';
export const METRICS_ONE_LIST_FILTERED_CHARGING = 'METRICS_ONE_LIST_FILTERED_CHARGING';
export const METRICS_ONE_LIST_ERROR = 'METRICS_ONE_LIST_ERROR';

export const METRICS_PDS_LIST_REQUEST = 'METRICS_PDS_LIST_REQUEST';
export const METRICS_PDS_LIST_FILTER_REQUEST = 'METRICS_PDS_LIST_FILTER_REQUEST';
export const METRICS_PDS_LIST_CHARGING = 'METRICS_PDS_LIST_CHARGING';
export const METRICS_PDS_LIST_FILTERED_CHARGING = 'METRICS_PDS_LIST_FILTERED_CHARGING';
export const METRICS_PDS_LIST_ERROR = 'METRICS_PDS_LIST_ERROR';

export const METRICS_PIP_LIST_REQUEST = 'METRICS_PIP_LIST_REQUEST';
export const METRICS_PIP_LIST_FILTER_REQUEST = 'METRICS_PIP_LIST_FILTER_REQUEST';
export const METRICS_PIP_LIST_CHARGING = 'METRICS_PIP_LIST_CHARGING';
export const METRICS_PIP_LIST_FILTERED_CHARGING = 'METRICS_PIP_LIST_FILTERED_CHARGING';
export const METRICS_PIP_LIST_ERROR = 'METRICS_PIP_LIST_ERROR';
