export const COLLABORATOR_LIST_REQUEST = 'COLLABORATOR_LIST_REQUEST';
export const RESET_STATE = 'RESET_STATE';
export const RESET_STORE = 'RESET_STORE';
export const TEAMS_REQUEST = 'TEAMS_REQUEST';
export const TEAMS_CHARGING = 'TEAMS_CHARGING';
export const TEAMS_ERROR = 'TEAMS_ERROR';
export const TEAMS_SECONDARY_CHARGING = 'TEAMS_SECONDARY_CHARGING';
export const TEAMS_SECONDARY_ERROR = 'TEAMS_SECONDARY_ERROR';
export const TEAMS_SECONDARY_REQUEST = 'TEAMS_SECONDARY_REQUEST';

export const USERS_CHARGING = 'USERS_CHARGING';
export const USERS_ERROR = 'USERS_ERROR';
export const USERS_REQUEST = 'USERS_REQUEST';
