export const RESET_STATE = 'RESET_STATE';
export const RESET_STORE = 'RESET_STORE';

export const SET_PERMISSIONS_REQUEST = 'SET_PERMISSIONS_REQUEST';

export const PERMISSIONS_CHARGING = 'PERMISSIONS_CHARGING';

export const PERMISSIONS_ERROR = 'PERMISSIONS_ERROR';
