export const RESET_STATE = 'RESET_STATE';
export const RESET_STORE = 'RESET_STORE';
export const PLAN_OWN_SELECTED = 'PLAN_OWN_SELECTED';

export const PLANS_OWN_LIST_REQUEST = 'PLANS_OWN_LIST_REQUEST';
export const PLANS_OWN_COLLABORATOR_LIST_REQUEST = 'PLANS_OWN_COLLABORATOR_LIST_REQUEST';
export const PLANS_OWN_COLLABORATORS_LIST_UPDATE = 'PLANS_OWN_COLLABORATORS_LIST_UPDATE';

export const PLANS_OWN_LIST_FILTER_REQUEST = 'PLANS_OWN_LIST_FILTER_REQUEST';
export const PLANS_OWN_LIST_SAVED = 'PLANS_OWN_LIST_SAVED';

export const PLANS_OWN_LIST_SAVE = 'PLANS_OWN_LIST_SAVE';
export const PLANS_OWN_LIST_UPDATE = 'PLANS_OWN_LIST_UPDATE';
export const PLANS_OWN_LIST_DELETE = 'PLANS_OWN_LIST_DELETE';
export const PLANS_OWN_LIST_DELETE_FILTERED = 'PLANS_OWN_LIST_DELETE_FILTERED';

export const PLANS_OWN_LIST_CHARGING = 'PLANS_OWN_LIST_CHARGING';
export const PLANS_OWN_SAVE_CHARGING = 'PLANS_OWN_SAVE_CHARGING';
export const PLANS_OWN_IMPORT_CHARGING = 'PLANS_OWN_IMPORT_CHARGING';

export const PLANS_OWN_LIST_FILTERED_CHARGING = 'PLANS_OWN_LIST_FILTERED_CHARGING';

export const PLANS_OWN_LIST_ERROR = 'PLANS_OWN_LIST_ERROR';
export const PLANS_OWN_IMPORT_ERROR = 'PLANS_OWN_IMPORT_ERROR';

export const SET_PLANS_OWN_METRICS_TABLE = 'SET_PLANS_OWN_METRICS_TABLE';
