export const RESET_STATE = 'RESET_STATE';
export const RESET_STORE = 'RESET_STORE';
export const PLAN_SELECTED = 'PLAN_SELECTED';

export const PLANS_LIST_REQUEST = 'PLANS_LIST_REQUEST';
export const PLANS_COLLABORATOR_LIST_REQUEST = 'PLANS_COLLABORATOR_LIST_REQUEST';
export const PLANS_COLLABORATORS_LIST_UPDATE = 'PLANS_COLLABORATORS_LIST_UPDATE';

export const PLANS_LIST_FILTER_REQUEST = 'PLANS_LIST_FILTER_REQUEST';
export const PLANS_LIST_SAVED = 'PLANS_LIST_SAVED';

export const PLANS_LIST_SAVE = 'PLANS_LIST_SAVE';
export const PLANS_LIST_UPDATE = 'PLANS_LIST_UPDATE';
export const PLANS_LIST_DELETE = 'PLANS_LIST_DELETE';
export const PLANS_LIST_DELETE_FILTERED = 'PLANS_LIST_DELETE_FILTERED';

export const PLANS_LIST_CHARGING = 'PLANS_LIST_CHARGING';
export const PLANS_SAVE_CHARGING = 'PLANS_SAVE_CHARGING';
export const PLANS_IMPORT_CHARGING = 'PLANS_IMPORT_CHARGING';

export const PLANS_LIST_FILTERED_CHARGING = 'PLANS_LIST_FILTERED_CHARGING';

export const PLANS_LIST_ERROR = 'PLANS_LIST_ERROR';
export const PLANS_IMPORT_ERROR = 'PLANS_IMPORT_ERROR';

export const SET_PLANS_METRICS_TABLE = 'SET_PLANS_METRICS_TABLE';
