export const RESET_STATE = 'RESET_STATE';
export const RESET_STORE = 'RESET_STORE';

export const SET_PREFERENCE_REQUEST = 'SET_PREFERENCE_REQUEST';

export const PREFERENCE_CHARGING = 'PREFERENCE_CHARGING';

export const PREFERENCE_ERROR = 'PREFERENCE_ERROR';
