name: Build & Deploy
on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.104.131.9.135}} # IP address of the server you wish to ssh into
          key: ${{secrets.af41118d96f8849e1e1ed579a0dad5ecfd0c6cbad7fc8c24297f2feb6fa17cc3}} # Private or public key of the server
          username: ${{ secrets.root }} # User of the server you want to ssh into
     
          script: |
            mkdir test 
            cd test 
            git clone git@github.com:Mulubwa17/ci-cd-to-digitalocean-with-github-actions.git 
            echo 'Deployment successful to digital ocean' 
            
          - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

